<?php

namespace Tests\Feature;

use App\Game\Game;
use App\Game\Pc28;
use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;

class GameTest extends TestCase
{

    protected static $game;


    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        self::$game = new Game();
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function testAddGame()
    {
        self::$game->addGame(new Pc28());

        if (count(self::$game->getGames()) < 1) {
            $this->assertTrue(false);
        }

        $this->assertTrue(true);

    }


    public function testGetCodes()
    {
        if (!is_array(self::$game->getCodes())) {
            $this->assertTrue(false);
        }
        $this->assertTrue(true);
    }
}
