<?php
/**
 * Created by PhpStorm.
 * User: sx
 * Date: 2017/12/16
 * Time: 09:33
 */

namespace App\Game;


/**
 * Class Pc28v25
 *北京幸运28  2.5倍场
 *
 * @package App\Game
 */
class Pc28v25 extends Pc28
{
    Const NAME = '北京幸运28-2.5倍场';

    public function lottery($code)
    {
        $result = []; //返回结果
        $code_list = [];   //开奖号码数组
        $result = parent::lottery($code); // TODO: Change the autogenerated stub
        $result['shunzi'] = null; //初始化
        $result['baozi'] = null;
        $result['duizi'] = null;
        $code_list = explode(',', $code);
        $result['shunzi'] = $this->shunzi($code_list);
        $result['baozi'] = $this->baozi($code_list);
        $result['duizi'] = $this->duizi($code_list);

        return $result;
    }


    /**
     * 顺子算法
     *
     * @param array $code
     */
    protected function shunzi(array $code_list)
    {
        //先排序 将开奖号从小到大排序  然后依次相减  有0跳过 看结果是否为1
        $code_list = array_sort($code_list);

        if (count($code_list) != 3) {
            throw new GameException(self::NAME.'顺子算法数据错误');
        }

        if ($code_list[0] == 0) {
            $result = $code_list['2'] - $code_list['1'];

            if ($result == 1) {
                return '顺子';
            } else {
                return '';
            }

        } else {
            $result1 = $code_list['1'] - $code_list['0'];
            $result2 = $code_list['2'] - $code_list['1'];

            if (($result1 == 1) && ($result2 == 1)) {
                return '顺子';
            } else {
                return '';
            }
        }

        return '';

    }


    //豹子算法 过滤相同值 取唯一 剩一个即为豹子
    protected function baozi(array $code_list)
    {
        $code_list = array_unique($code_list);

        if (count($code_list) == 1) {
            return '豹子';
        }

        return '';
    }


    //对子算法 过滤相同  数组长度为2即为对子
    protected function duizi(array $code_list)
    {

        $code_list = array_unique($code_list);
        if (count($code_list) == 2) {
            return '对子';
        }

        return '';

    }


    //开奖
    public function rule($bet, $open_num, $code_info_arr)
    {
        $lottery = $this->lottery($open_num);
        $time = 0;
        if (is_numeric($bet)) {
            if ($bet == $lottery['num']) {
                $time = 11;
            }
        } else {

            switch ($bet) {
                case '单' :
                case '双' :
                    if ($bet == $lottery['danshuang']) {
                        $time = 2.5;
                    }
                    if ($bet == '单' && $lottery['num'] == 13) {
                        $time = 1.2;
                    }
                    if ($bet == '双' && $lottery['num'] == 14) {
                        $time = 1.2;
                    }

                    if ($lottery['shunzi'] || $lottery['baozi']
                        || $lottery['duizi']
                    ) {
                        $time = 0;
                        if ($bet == '单' && $lottery['num'] == 13) {
                            $time = 1.2;
                        }
                        if ($bet == '双' && $lottery['num'] == 14) {
                            $time = 1.2;
                        }
                    }

                    break;
                case '小单' :
                case '小双' :
                case '大单' :
                case '大双' :
                    if ($bet == $lottery['zuhe']) {
                        if ($bet == '小单' || $bet == '大双') {
                            $time = 5;
                        } else {
                            $time = 5;
                        }
                    }
                    if ($lottery['shunzi'] || $lottery['baozi']
                        || $lottery['duizi']
                    ) {
                        $time = 0;
                        if ($bet == '小单' && $lottery['num'] == 13) {
                            $time = 1.2;
                        }
                        if ($bet == '大双'
                            && $lottery['num'] ==
                            14
                        ) {
                            $time = 1.2;
                        }

                    }


                    break;
                case '大' :
                case '小' :
                    if ($bet == $lottery['daxiao']) {
                        $time = 2.5;
                    }

                    if ($lottery['shunzi'] || $lottery['baozi']
                        || $lottery['duizi']
                    ) {
                        if ($bet == $lottery['daxiao']) {
                            $time = 1.5;
                        }
                        if ($bet == '小' && $lottery['num'] == 13) {
                            $time = 1.2;
                        }
                        if ($bet == '大' && $lottery['num'] == 14) {
                            $time = 1.2;
                        }

                    }

                    break;
                case '极大' :
                case '极小' :
                    if ($bet == $lottery['jizhi']) {
                        $time = 11;
                    }
                    break;

                case '豹子':
                    if ($bet == $lottery['baozi']) {
                        $time = 50;
                    }
                    break;
                case '顺子':
                    if ($bet == $lottery['shunzi']) {
                        $time = 12;
                    }
                    break;
                case '对子':
                    if ($bet == $lottery['duizi']) {
                        $time = 3;
                    }
                    break;
            }

        }

        return $time;

    }


}